from setuptools import setup, find_packages

setup(
    name="movie-recommendation-system",
    version="1.0.0",
    author="TLTN",
    author_email="tltnlovelala@gmail.com",
    description="A comprehensive movie recommendation system using collaborative filtering",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/TLTN/movie-recommendation-system",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "scipy>=1.7.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "plotly>=5.0.0",
        "flask>=2.0.0",
        "tensorflow>=2.8.0",
        "torch>=1.10.0",
        "pyyaml>=6.0",
        "joblib>=1.1.0",
        "tqdm>=4.62.0",
        "surprise>=1.1.1",
        "implicit>=0.6.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0",
            "black>=21.0",
            "flake8>=4.0",
            "jupyter>=1.0.0",
            "notebook>=6.4.0",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="recommendation system, collaborative filtering, machine learning, movielens",
)